version: "3.8"

services:
  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: cashflow-postgres
    restart: always
    environment:
      POSTGRES_USER: cashflow
      POSTGRES_PASSWORD: cashflow
      POSTGRES_DB: cashflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Zookeeper (need for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cashflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cashflow-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # Go App(CashFlow)
  app:
    build: .
    container_name: cashflow-app
    depends_on:
      - postgres
      - kafka
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: cashflow
      DB_PASSWORD: cashflow
      DB_NAME: cashflow_db
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
